"""Changes in Room

Revision ID: bc6a52338a56
Revises: 1a8a337201dd
Create Date: 2024-02-25 21:41:05.197035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6a52338a56'
down_revision: Union[str, None] = '1a8a337201dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_column('rooms', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'price')
    # ### end Alembic commands ###
